feat: add `arc-2pt` to draw an arc between two points
cetz-package/cetz pull request #417
Opened 2023-12-22 09:22 UTC by RubixDev

Based on [this Discord discussion], this PR adds a new draw function called `arc-2pt` which draws an arc given a start and end point, the radius, and two boolean flags. This is the arc parameterization that SVG uses, and they describe how to convert between this and the "center parameterization" which the `arc` function uses [here](https://www.w3.org/TR/SVG/implnote.html#ArcConversionEndpointToCenter).

As part of the PR I also added a new `rotation` style to the normal `arc` to define an angle to rotate the ellipse by before calculating the arc.

## Things left to do:
- [ ] fix compass anchors on arcs with rotation (i'm not sure where exactly they even should be)
- [ ] add docs for `arc-2pt`
- [ ] test compatibility with z axis
- [ ] fix current position after rotated arcs
- [ ] maybe move some of the `arc-2pt` args to a new style root?

---

Before I can finish these things I would like to hear you opinions and insights on them, and maybe also have you review the current changes.

2023-12-22 14:03 UTC, johannes-wolf requested changes

2023-12-22 14:03 UTC, johannes-wolf commented on src/draw/shapes.typ
> +            -arc-start.at(1),
This is not correct. Transform points using `util.apply-transform` first, do not expect flipped y-direction.

2023-12-22 14:38 UTC, johannes-wolf commented
Can't we just determine the radii, call the draw function of `arc` with a modified context object that contains the rotation?

2023-12-29 07:16 UTC, RubixDev commented
> Can't we just determine the radii, call the draw function of `arc` with a modified context object that contains the rotation? Without having the `rotate:` argument in `arc`. I do not really like that.

note the rotation isn't just rotating the arc, it's rotating the ellipse of which the arc is calculated. It's certainly possible to make `arc-2pt` return a `group` with a local `rotate` transformation, but then this ellipse rotation feature wouldn't also be available for the normal `arc`, and we would also have to create the anchors from scratch.

2023-12-29 07:17 UTC, RubixDev commented on src/draw/shapes.typ
> +      // rotate around arc-start by -style.rotation
but `radius` is a style key, why should `rotation` not also be if it also just has an effect on the underlying ellipses?

2023-12-29 11:26 UTC, johannes-wolf commented on src/draw/shapes.typ
> +      // rotate around arc-start by -style.rotation
Yes, I was wrong.

2024-05-18 11:52 UTC, closed without merging